# Generated by Django 2.2.14 on 2020-11-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='init_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='init_time',
            field=models.TimeField(),
        ),
    ]
