# Generated by Django 2.2.14 on 2020-11-29 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classroom', models.CharField(max_length=30)),
                ('students_limit', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30)])),
                ('init_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Name',
                'verbose_name_plural': 'Names',
                'ordering': ['name'],
            },
        ),
    ]
