# Generated by Django 2.2.14 on 2020-11-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students_limit',
        ),
    ]
