# Generated by Django 2.2.14 on 2020-11-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_students_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='init_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='init_time',
            field=models.TimeField(null=True),
        ),
    ]
